### ISSUE TITLE
List 5 topics you would like to discuss work on

### ISSUE THREAD

**Issue by calvinsettachatgul** [calvinsettachatgul/cale#1]
5 topics then we can break down into sub topics

**Comment by calvinsettachatgul** [comment]
Hey are you getting these notifications?

**Comment by calvinsettachatgul** [comment]
@lwa3000

**Comment by calvinsettachatgul** [comment]
I was able to do this

**Comment by Lwa3000** [comment]
Hey, we meeting up tonight?! Looking forward to it
